<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>cyberpunk-save-editor</AssemblyName>
    <RootNamespace>CyberpunkSaveEditor</RootNamespace>
    <Version>1.0.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolvenKit.RED4" Version="8.20.0" />
  </ItemGroup>

</Project>
